version: '3'
services:
  client:
    image: client/cloutcompanion:v1
    build:
      dockerfile: Dockerfile.dev
      context: client
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules/
      - ./client:/app
    links:
      - server
  server:
    image: server/cloutcompanion:v1
    build:
      dockerfile: Dockerfile.dev
      context: server
    restart: always
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '5000:5000'
    links:
      - mongo
  # tests:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: server
  #   volumes:
  #     - /app/node_modules
  #     - ./server:/app
  #   links:
  #     - mongo
  #   command: ['npm', 'run', 'test-watch']
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
